travisjeffery/timecop

- lib/timecop/time_extensions.rb
- lib/timecop/time_stack_item.rb
- lib/timecop/timecop.rb
- test/test_helper.rb
Eliminates various warnings issued by ruby in its verbose warning mode (`ruby -w`, or `$VERBOSE = true`, or `RSpec.config.warnings = true`).
This was an issue for me in an app that I'm testing using `RSpec.config.warnings = true` (as recommended by the default RSpec generator); there are only a few warnings due to Timecop, but they get repeated *many* times.
> Eliminate ruby warnings

- lib/timecop/time_stack_item.rb
- test/time_stack_item_test.rb
- test/timecop_test.rb
Note that the first comment fixes the test, but actually breaks the build. The second commit fixes things.
> Fix a bug wrt to datetime precision after travel

- lib/timecop/timecop.rb
- test/timecop_test.rb
Consider this example:
```ruby
Timecop.travel(Time.now - (1 * 24 * 60 * 60)) do
puts Time.now.to_s
Timecop.return { puts Time.now.to_s; raise 'foo!' } rescue nil
puts Time.now.to_s
end
```
Console output:
```
2014-09-10 14:05:55 -0700
2014-09-11 14:05:55 -0700
2014-09-11 14:05:55 -0700
```
Errors raised in a `Timecop.return` block mean the previous time is never restored, undoing any freezes or travels. This PR simply adds an `ensure` statement in `Timecop#return` that ensures the current stack always gets restored, even when an error occurs in the `yield`.
> Issue when an error is raised in a Timecop.return block

- README.markdown
`foo "bar" {}` is not parsed as `foo("bar") {}`, but as `foo("bar" {})`, which is invalid syntax.
> Fix a syntax error in the README

- lib/timecop/timecop.rb
- test/timecop_test.rb
This PR adds `Timecop.frozen?` which returns whether or not the cop has anything on its stack
This lets us add this to our global test teardown:
```rb
raise "BRR! IT'S COLD IN HERE!" if Timecop.frozen?
```
> add Timecop.frozen?

- test/test_helper.rb
- test/time_stack_item_test.rb
- test/timecop_date_parse_test.rb
- test/timecop_test.rb
- test/timecop_with_active_support_test.rb
- test/timecop_without_date_but_with_time_test.rb
- test/timecop_without_date_test.rb
- reply on bundler/setup setting up the load paths
- do not require rubygems, it is not recommended + unnecessary
- simplify mocha require
- enable running `ruby test/timecop_test.rb` without having to specify `-I.`
- load bundler before loading activesupport in timecop_with_activesupport test so there will be no version conflict when run without bundle exec
@travisjeffery
> simplify test setup

- lib/timecop/time_stack_item.rb
- test/time_stack_item_test.rb
Allows Timecop to accept floats for the `.freeze` and `.travel` methods. 
Most common use case is probably in ActiveSupport's Time extensions (`1.year`, `3.5.hours`) which can return floats.
Includes tests.
Should fix issues https://github.com/travisjeffery/timecop/issues/145 and https://github.com/travisjeffery/timecop/issues/174.
:cactus:
> Add support for Float arguments to Timecop.freeze, Timecop.travel

- Gemfile
Prevent dependency on Ruby 2.2.2 when switching Ruby versions with rvm in Travis job.
As described in issue: https://github.com/travisjeffery/timecop/issues/193
> require rack < 2.0.0 for some ruby versions

- lib/timecop/time_extensions.rb
- test/timecop_date_parse_test.rb
`DateTime.parse([])` actually throws a `TypeError` in default Ruby, but a `NoMethodError` when timecop is required. This change fixes that difference.
> Adhere to Ruby DateTime implementation

- lib/timecop/timecop.rb
- test/timecop_test.rb
We have a use for Timecop in production code (executing queries as if it were the top of the hour), but ran into an issue with a threaded web server.
With this PR, setting `Timecop.thread_safe = true` will switch Timecop to using a `Thread.current` stack instead of a singleton one.
cc @zendesk/rules
> add thread-safe option to timecop

- lib/timecop/time_extensions.rb
- test/timecop_date_parse_shorcut_freeze_test.rb
Relax the check on incoming date_hash to return the unaltered
parsed_date if only year and month are supplied.
I submitted issue #205 for this.
> Allow parsing of month/year dates without applying offset

- lib/timecop/time_extensions.rb
- test/timecop_test.rb
> fix Date.strptime monkeypatch

- lib/timecop/timecop.rb
- test/timecop_test.rb
Hey
I was using Timecop recently and it was just weird for me that there is to unfreeze time I had to use return method. `unfreeze` was just more common sense in my opinion and more consistent with rest of API so I thought that maybe adding just alias would be nice 😄
> Timecop#unfreeze - Add alias for Timecop#return

- test/time_stack_item_test.rb
The test_timezones_apply_dates test actually fails to test
timezones. It is comparing the local time with the time zone
specific time. Therefore the test actually only "passes" if the
time zone is to the "west" of the local time zone. A person in
the America/Los_Angeles time zone will receive a failure when
running the current test as the Central Time zone is to the "east".
Change the test to use Time.zone.now for the comparison date
> Fix testing timezone dates

- lib/timecop/time_extensions.rb
- test/timecop_test.rb
When calling the original `Date.strptime` without a day, the day is set to `1`. Timecop should probably not change that behavior.
```ruby
irb(main):002:0> require "date"
=> true
irb(main):003:0> Date.strptime('1999-04', '%Y-%m')
=> #<Date: 1999-04-01 ((2451270j,0s,0n),+0s,2299161j)>
irb(main):004:0> Date.new(1999, 4)
=> #<Date: 1999-04-01 ((2451270j,0s,0n),+0s,2299161j)>
```
In this PR I added a small test case for parsing a Date without a "day", and expect the day to be `1`; In order to make this spec pass, I change the implementation of `strptime_with_mock_date` to not specify the "day" of the created date to be the "current day" when no specific day is provided, but to default to the first day of the month.
> Fix strptime without day

- test/date_strptime_scenarios.rb
This PR includes some new Date::strptime tests. Please note that i have commented out or skipped the tests that are failing. One step towards a better strptime implementation will be getting all these passing. They are inspired by the jruby test suite for Date. A lot of these use strftime for a given date, and then expect strptime to convert that string back into the original date. Our strptime doesn't work for a bunch of the formats.
Another thing that I am thinking about is that we are monkeypatching strptime, and delegating to _strptime... This might be a problem. Anyone using _strptime in their codebase will be confused since that won't adhere to the frozen date. I'm not really sure we're on the right track with our implementation.
> Include more date strptime test scenarios

- lib/timecop/timecop.rb
- test/timecop_test.rb
The [`thread_safe` option](https://github.com/travisjeffery/timecop/pull/184) introduced to Timecop `v0.9.0` (and still present in `v0.9.1`) contains a major bug: The time is not automatically returned to its original state, when `Timecop.freeze` or `Timecop.travel` are called *with a block*.
The original PR for the feature actually worked fine, but was broken by [this separate commit line](https://github.com/travisjeffery/timecop/commit/e1eb6789d8df873d7dd75526dafc7655627bf1ba#diff-e2a91a7e1d108ef45b81d12313b150faR203), in [this PR](https://github.com/travisjeffery/timecop/pull/202).
Minimal reproduction example (as seen from the test in this PR):
Timecop.thread_safe = true
date = Time.local(2017, 10, 8)
Timecop.freeze(date) { }
puts Time.now  # => 2017-10-08 00:00:00 +0100
This bug …
> Return to previous date after block when in threadsafe mode

- lib/timecop/time_extensions.rb
As of https://github.com/ruby/ruby/pull/4010, `Time.new` now accepts an optional keyword argument.
This means the monkey patch here will break in newer Ruby versions, because Ruby now requires keyword arguments be handled separately from other arguments.
Check if `ruby2_keywords` is defined (Ruby 2.7+), and use it if it is, which will force the previous behavior.
> Add support for ruby-head (3.1)

- .github/workflows/CI.yml
Also tests against `ruby-head` and fixes a failure on it.
The `ruby/setup-ruby` action doesn't support Ruby 1.9 or 2.0, so dropping those. If support is still necessary, I can explore workarounds.
Sample build: https://github.com/mlarraz/timecop/actions/runs/496778019
> Use Github Actions for CI

- .github/workflows/CI.yml
Add a weekly schedule to run the github CI action each Sunday, this will help detect any breakage from used gems/ruby/ci in the case nothing changes in this gem for some time
> Update CI.yml to add a weekly schedule

- Gemfile
newer ruby does not have net ftp in stdlib. nokogiri needs that so need to update nokogiri
> fixing ruby head build

- lib/timecop/time_extensions.rb
- test/date_strptime_scenarios.rb
Potential fix for https://github.com/travisjeffery/timecop/issues/377
> Fix %Y date format %Y

- lib/timecop/timecop.rb
Previously all timecop instance methods were private and we would call them from the class methods using send(). This commit achieves a similar effect (making the instance methods inaccessible to users) by making `instance` private.
Using standard method calls instead of send should be slightly faster as it reduces method lookups.
> Avoid Kernel#send()

- Dockerfile
- bin/console
Add bin/console. #298
bundle console is Deprecated.
```bash
$ bundle console
[DEPRECATED] bundle console will be replaced by `bin/console` generated by `bundle gem <name>`
```
```bash
$ bin/console
irb(main):001:0>
```
> Add bin/console

- lib/timecop/time_extensions.rb
- test/date_strptime_scenarios.rb
Timecop is incompatible with the newest patch version of Psych (4.0.5) because of [this change](https://github.com/ruby/psych/compare/v4.0.4..v4.0.5#diff-6a459e056cadf37665f54005bd2dde09d9ba8e66c9807eb0dc67145f9b841771L66-R66).
Timecop only allows Date#strptime to be called with the default of Date::ITALY as the fourth argument. This fourth argument is the "day of calendar reform" for leap years.  Dates pre-reform are Julian calendar dates, which have leap years every 4 years. Dates after reform are Gregorian calendar dates, which have more complicated leap year logic (every 4 years, except if the year is divisible by 100 and not by 400). https://en.wikipedia.org/wiki/Gregorian_calendar
Psych starts calling strptime with Date::GREGORIAN as of 4.0.5 (I'm not sure why, but it's a legal use …
> Allow other "dates of calendar reform" in Date#strptime

- Gemfile
The scheduled CI with Ruby 2.3, 2.4 and 2.5 fails these days.
(e.g. https://github.com/travisjeffery/timecop/actions/runs/3120487421)
I couldn't fully figure out the root cause, but it appears to be caused by the installation of activesupport v3.1.12.
Requiring activesupport v4.2 or higher solved this problem.
> Explicitly require activesupport >= 4.2

- Gemfile
Reverts travisjeffery/timecop#391 This didn't end up fixing the build. We played a hunch, but ruby 2.5 build still failing.
> Revert "Explicitly require activesupport >= 4.2"

- .github/workflows/CI.yml
This PR attempts to fix failing CI with Ruby 2.5.
refs: #391
[ruby/setup-ruby](https://github.com/ruby/setup-ruby) provides the function to cache `bundle install`, but sometimes this cache seems to corrupt.
https://github.com/ruby/setup-ruby#dealing-with-a-corrupted-cache
> In some rare scenarios (like using gems with C extensions whose functionality depends on libraries found on the system at the time of the gem's build) it may be necessary to ignore contents of the cache and get and build all the gems anew. In order to achieve this, set the `cache-version` option to any value other than `0` (or change it to a new unique value if you have already used it before.)
The most recent logs show that psych builds are failing, which is exactly the situation. …
> Dealing with a corrupted cache

- .github/workflows/CI.yml
```
Installing Bundler
Bundler 2 requires Ruby 2.3+, using Bundler 1 on Ruby <= 2.2
/opt/hostedtoolcache/Ruby/2.2.10/x64/bin/gem install bundler -v ~> 1.0
ERROR:  While executing gem ... (RuntimeError)
Marshal.load reentered at marshal_load
Took   0.33 seconds
Error: The process '/opt/hostedtoolcache/Ruby/2.2.10/x64/bin/gem' failed with exit code 1
```
Our CI builds are failing because we would need to maintain different versions of bundler for these ancient rubies. 2.2 was EOL on (31 Mar 2018)... I'm just going to stop testing our code there.  According to this https://github.com/ruby/setup-ruby/issues/496 there is no workaround.
> remove ruby 21 and 22 from matrix

- lib/timecop/time_stack_item.rb
I spotted this in a memory_profiler report for some of my app's specs. timecop was showing up in the list of gems with the most allocated memory.
This dup appears unnecessary. The code I can see isn't making modifications to the object, and I would expect `at` to return an new object anyways.
memory_profiler before:
allocated memory by location
-----------------------------------
...
49_836_480  /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/timecop-0.9.6/lib/timecop/time_stack_item.rb:59
...
allocated objects by location
-----------------------------------
...
934_434  /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/timecop-0.9.6/lib/timecop/time_stack_item.rb:59
...
memory_profiler after:
allocated memory by location …
> Reduce memory by not duplicating an argument

- lib/timecop/time_extensions.rb
In https://github.com/ylecuyer/puma-status I had a red build because timecop isn't yet compatible with ruby 3.1
```
Run bundle exec rspec
/home/runner/.rubies/ruby-head/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:29: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/home/runner/.rubies/ruby-head/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/home/runner/.rubies/ruby-head/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/home/runner/.rubies/ruby-head/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: …
```
> Better: Add ruby 3.1 compatibility.

- lib/timecop/time_extensions.rb
Reverts travisjeffery/timecop#279
This PR isn't working on ruby 3.1 build
```
/home/runner/work/timecop/timecop/lib/timecop/time_extensions.rb:7:in `mock_time': stack level too deep (SystemStackError)
```
> Revert "Better: Add ruby 3.1 compatibility."

- lib/timecop/time_extensions.rb
A variable `date_hash` appears two times, so I removed first one.
> Remove unused variable in DateTime.parse_with_mock_date

- lib/timecop/time_extensions.rb
- test/date_strptime_scenarios.rb
While I was trying to handle the non-commercial week of the year (which is where the week starts on a sunday). I realized there were scenarios where you could mix commercial date stuff with non-commercial date stuff so had to come up with a consolidated way to handle that. I came up with always converting day of week to a monday start based day of week.
This made all our other scenarios pass without so much conditional logic and seems to handle this mix/match stuff as well.
> 380 week of year fix

- lib/timecop/time_extensions.rb
- test/date_strptime_scenarios.rb
While trying to get the rest of the TODO date formats to work I found a bug with the previous week based date handling. If we were given a date like Date.strptime('2006 23 0', '%Y %U %w') our code would come up with 2006/6/11. But it is actually 2006/6/4
The problem is that we were trying to use Date.commercial for everything but some weeks a given sunday based date isn't even in the same week as the monday based weeks that Date.commercial uses. See below. 6/4 is in the 22nd commercial week but 23rd non-commercial
```
2006 - 23rd week of the year...
Monday start    -   Sunday start
[Mon 6/5] 23 1  -  [Sun 6/4] 23 0
[Tu  6/6] 23 2  -  [Mon 6/5] 23 1
[We  6/7] 23 3  -  [Tu  6/6] 23 2
[Th  6/8] 23 4  -  [We  6/7] 23 3
[Fr  6/9] 23 5  -  [Th  6/8] 23 4
[Sa 6/10] 23 6  -  [Fr  6/9] 23 5
[Su …
```
> fix week based dates

- History.md
- lib/timecop/timecop.rb
- test/timecop_test.rb
In a recent Timecop release (0.9.7, commit [c57a1fc](https://github.com/travisjeffery/timecop/commit/c57a1fce6468f594738674376dbcb29fe9dc1627)), a fix was made to the boolean method`#frozen?` which previously returned `true` if Timecop was active at that instance in time (frozen, scaled or travelled). This method was changed so that only returned `true` if Timecop was in a frozen state. Once this change was made it was no longer possible to check if Timecop was in a `scaled` or `travelled` state.
As a result of this change, our automated test suite, which relied on the previous behaviour of `frozen?` failed (we used it to check if Timecop present in any way in a database helper, and it affected how our automated factory objects were being created where dates are involved). We discovered …
> Add methods to allow Timecop instance checking if in a travelled or scaled state

- README.markdown
- lib/timecop/time_extensions.rb
- lib/timecop/time_stack_item.rb
- lib/timecop/timecop.rb
- test/timecop_test.rb
- test/timecop_with_process_clock_test.rb
I am interested in being able to use Timecop with `Process.clock_gettime`. I saw https://github.com/travisjeffery/timecop/issues/220 (the request for this) and https://github.com/travisjeffery/timecop/pull/258 (the PR that implemented it).
This code is nearly the same as https://github.com/travisjeffery/timecop/pull/258; I have only made minor changes.
> Add `Process.clock_gettime` support

- History.md
- README.markdown
- lib/timecop/time_extensions.rb
- lib/timecop/timecop.rb
- lib/timecop/version.rb
- test/timecop_with_process_clock_test.rb
based on PR 426. i couldn't figure out how to do this another way.
> Optional clock gettime 2

- History.md
- lib/timecop/time_stack_item.rb
- test/time_stack_item_test.rb
I ran tests locally for this PR and THOUGHT they passed but I must have screwed up. Reverting for now.
Reverts travisjeffery/timecop#421
> Revert "Calculate travel_offset to align with the precision of argument to Timecop.travel"

- lib/timecop/time_extensions.rb
- lib/timecop/time_stack_item.rb
- test/timecop_with_process_clock_test.rb
- timecop.gemspec
https://github.com/travisjeffery/timecop/pull/419 had to check for Ruby >= 2.1.0, but maybe this is a good time to bump the Ruby version in the library and cut a release?
(I also noticed CI seems to test back to 2.3, so maybe we consider going up even further.)
> Require Ruby >= 2.1.0
